Repository AxisCommunications/docker-acap, pull requests merged in 2024-04, with the labels that each got.

#162 Allow multiple headers in certs
  app/dockerdwrapper.c
Labels: rootless

#140 Change to ACAP SDK 4.13
  Dockerfile
  app/dockerdwrapper.c
Labels: after_LTS

#141 Use AxParameter library from native SDK
  Dockerfile
  app/dockerdwrapper.c
Labels: after_LTS

#167 Introduce constants for application name and directories
  app/Makefile
  app/dockerdwrapper.c
Labels: after_LTS

#145 Migrate data root
  app/dockerdwrapper.c
Labels: after_LTS

#166 Fail installation on device without container support
  app/postinstallscript.sh
Labels: after_LTS

#168 Update version to 2.0 for coming release
  README.md
  app/manifest.json
Labels: after_LTS

#208 Manifest and postinstall updated for rootless
  Dockerfile
  app/manifest.json
  app/postinstallscript.sh
Labels: rootless

#206 Add env variables for rootless
  app/dockerdwrapper.c
Labels: rootless

#193 Create rootlesskit command
  app/app_paths.h
  app/dockerdwrapper.c
Labels: rootless

#213 Clean up docker.pid file in /var/run/user
  app/dockerdwrapper.c
Labels: rootless

#133 Updated documentation for rootless release
  README.md
Labels: documentation, after_LTS, rootless

#226 Set IPC socket group ownership to addon
  app/dockerdwrapper.c
Labels: rootless

#228 Remove SD Card migration
  app/dockerdwrapper.c
Labels: rootless

#234 Add sdk group
  README.md
  app/manifest.json
Labels: rootless
